sudo: required
language: java
install: true

services:
  - docker

jobs:
  include:
    - stage: test
      if: branch = develop and env(operation) = local

      # Minikube installation taken from: https://github.com/LiliC/travis-minikube/blob/minikube-30-kube-1.12/.travis.yml
      # We need the systemd for the kubeadm and it's default from 16.04+
      dist: xenial

      before_script: sudo sh travis/setupCluster.sh

      script: cd terraform/test && terraform init -input=false

      deploy:
        - provider: script
          skip_cleanup: true
          script: sh ${TRAVIS_BUILD_DIR}/travis/test_template-svce.sh
          on:
            branch: develop

    - stage: deploy on network of resources
        if: branch = develop and env(operation) = deploy_nor

        dist: bionic
        before_script:
        script: sh ${TRAVIS_BUILD_DIR}/travis/setupOpenstack.sh
        deploy:
          - provider: script
            skip_cleanup: true
            script: cd ${TRAVIS_BUILD_DIR}/terraform/NoR/ && terraform apply -auto-approve -var-file=inventory/cf2-kube/cluster.tfvars openstack/
            on:
              branch: develop

    - stage: undeploy from network of resources
      if: branch = develop and env(operation) = undeploy_nor
      
      dist: bionic
      before_script:
      script: sh ${TRAVIS_BUILD_DIR}/travis/setupOpenstack.sh
      deploy:
        - provider: script
          skip_cleanup: true
          script: cd ${TRAVIS_BUILD_DIR}/terraform/NoR/ && terraform destroy -auto-approve openstack/
          on:
            branch: develop
                

import:
  - docs/.travis.yml

notifications:
  slack: eoepca:Msk9hjQKAbwSYcVWiepenPim
  email:
    recipients:
      - a.person @acme.com
      - a.n.other@acme.com
    on_success: never # default: change
    on_failure: never # default: always
