version: "3.5"

#sudo /usr/local/bin/docker-compose -f docker-compose-dev.yml up -d
#sudo /usr/local/bin/docker-compose  -f docker-compose-dev.yml stop
#sudo /usr/local/bin/docker-compose  -f docker-compose-dev.yml down
services:

  web-wf-exe:
    build:
      context: 3ty/workflow_executor/webinterface
      dockerfile: Dockerfile
    image: web-wf-exe:1.0
    hostname: webwf.org
    container_name: web-wf-exe
    networks:
      - eoepca_network
#    ports:
#      - "9999:80"

  ades:
    image: eoepca/proc-ades:travis__186
    container_name: ades
    networks:
      - eoepca_network
    ports:
      - target: 80
        published: 8888
        protocol: tcp
        mode: host
    volumes:
      # configuration volume
      - ./config:/var/etc/ades:ro
      # da rimuovere - ./:/work
      - ./:/work
    links:
      - web-wf-exe
    depends_on:
      - web-wf-exe


networks:
  eoepca_network:
    driver: bridge
    name: eoepcanetwork

#docker rmi t2cm:0.1 t2sm:0.1 t2sd:0.1
#  docker-compose rm -f
# docker-compose up -d
# docker-compose stop
#sudo /usr/local/bin/docker-compose -f docker-compose-dev.yml up
#sudo /usr/local/bin/docker-compose -f docker-compose-dev.yml rm
#  docker exec -ti -e COLUMNS="`tput cols`" -e LINES="`tput lines`" ades  bash