apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: proc-ades-wps
    env: proc-ades-wps
  name: proc-ades-wps
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: proc-ades-wps
        env: proc-ades-wps
    spec:
      nodeSelector:
        nst2pc_wps: enabled
      containers:
      - name: proc-ades-wps
        image: eoepca/proc-ades:travis_develop_100
        imagePullPolicy: Always


      restartPolicy: Always



#https://kubernetes.io/docs/concepts/configuration/secret/
##kubectl create --namespace=eoepca -f xxxxxx.yaml
