apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  ppImagePullSecrets.json: {{  toJson .Values.workflowExecutor.imagePullSecrets | quote }}
  kubeconfig: {{ tpl (.Files.Get .Values.workflowExecutor.kubeconfig) . | quote }}
  maincfg: {{ tpl (.Files.Get .Values.wps.maincfgtpl) . | quote }}
  maincwl.cwl: {{ tpl (.Files.Get .Values.workflowExecutor.maincwl) . | quote }}
  