apiVersion: v1
kind: PersistentVolume
metadata:
  name: ades-config-pv
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    # type: Directory
    path: /var/ades/config