---
apiVersion: batch/v1
kind: Job
metadata:
  name: calrissianjob
spec:
  template:
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      initContainers:
        - name: calrissian
          image: dukegcb/calrissian:latest
          imagePullPolicy: IfNotPresent
          command: ["calrissian"]
          args:
            - "--stdout"
            - "/calrissian/output-data/revsort-output.json"
            - "--stderr"
            - "/calrissian/output-data/revsort-stderr.log"
            - "--max-ram"
            - "4G"
            - "--max-cores"
            - "2"
            - "--tmp-outdir-prefix"
            - "/calrissian/tmpout/"
            - "--debug"
            - "--tmpdir-prefix"
            - "/calrissian/tmpout/"
            - "--leave-tmpdir"
            - "--leave-container"
            - "--no-read-only"
            - "--outdir"
            - "/calrissian/output-data/"
            - "/calrissian/input-data/revsort-array.cwl"
            - "/calrissian/input-data/revsort-array-job.json"
          volumeMounts:
            - mountPath: /calrissian/input-data
              name: calrissian-input-data
            - mountPath: /calrissian/tmpout
              name: calrissian-tmpout
            - mountPath: /calrissian/output-data
              name: calrissian-output-data
          env:
            - name: CALRISSIAN_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      containers:
        - name: stage-out
          image: terradue/c7-stage-out:1.5
          command: ["stage-out"]
          args:
            - "--source"
            - "/calrissian/output-data/revsort-output.json"
            - "--endpoint"
            - "$(CATALOG_ENDPOINT)"
            - "--username"
            - "$(CATALOG_USERNAME)"
            - "--apikey"
            - "$(CATALOG_APIKEY)"
            - "--store-host"
            - "$(STORAGE_HOST)"
            - "--store-username"
            - "$(STORAGE_USERNAME)"
            - "--store-apikey"
            - "$(STORAGE_APIKEY)"
            - "--job"
            - "t2workflow123"
            - "--outputfile"
            - "/calrissian/output-data/stac-output.out"
          volumeMounts:
            - mountPath: /calrissian/input-data
              name: calrissian-input-data
            - mountPath: /calrissian/tmpout
              name: calrissian-tmpout
            - mountPath: /calrissian/output-data
              name: calrissian-output-data
          env:
            - name: CATALOG_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: procades-secret
                  key: catalog_endpoint
            - name: CATALOG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: procades-secret
                  key: catalog_username
            - name: CATALOG_APIKEY
              valueFrom:
                secretKeyRef:
                  name: procades-secret
                  key: catalog_apikey
            - name: STORAGE_HOST
              valueFrom:
                secretKeyRef:
                  name: procades-secret
                  key: storage_host
            - name: STORAGE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: procades-secret
                  key: storage_username
            - name: STORAGE_APIKEY
              valueFrom:
                secretKeyRef:
                  name: procades-secret
                  key: storage_apikey

      restartPolicy: Never
      volumes:
        - name: calrissian-input-data
          persistentVolumeClaim:
            claimName: calrissian-input-data
        - name: calrissian-tmpout
          persistentVolumeClaim:
            claimName: calrissian-tmpout
        - name: calrissian-output-data
          persistentVolumeClaim:
            claimName: calrissian-output-data
