---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{jobname}}
spec:
  template:
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
        - name: calrissian
          image: dukegcb/calrissian:latest
          imagePullPolicy: IfNotPresent
          command: ["calrissian"]
          args:
            - "--stdout"
            - "{{stdout}}"
            - "--stderr"
            - "{{stderr}}"
            - "--max-ram"
            - "{{max_ram}}"
            - "--max-cores"
            - "{{max_cores}}"
            - "--tmp-outdir-prefix"
            - "{{tmp_outdir_prefix}}"
            - "--debug"
            - "--tmpdir-prefix"
            - "{{tmpdir_prefix}}"
            - "--leave-tmpdir"
            - "--leave-container"
            - "--no-read-only"
            - "--outdir"
            - "{{outdir}}"
            - "{{argument1}}"
            - "{{argument2}}"
          volumeMounts:
            - mountPath: {{volumemount_input_data_mount_path}}
              name: {{volumemount_input_data_name}}
            - mountPath: {{volumemount_tmpout_mount_path}}
              name: {{volumemount_tmpout_name}}
            - mountPath: {{volumemount_output_data_mount_path}}
              name: {{volumemount_output_data_name}}
          env:
            - name: CALRISSIAN_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

      restartPolicy: Never
      volumes:
        - name: {{volumemount_input_data_name}}
          persistentVolumeClaim:
            claimName: {{volumemount_input_data_name}}
        - name: {{volumemount_tmpout_name}}
          persistentVolumeClaim:
            claimName: {{volumemount_tmpout_name}}
        - name: {{volumemount_output_data_name}}
          persistentVolumeClaim:
            claimName: {{volumemount_output_data_name}}
