---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{jobname}}
spec:
  template:
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: calrissian
          image: dukegcb/calrissian:latest
          imagePullPolicy: IfNotPresent
          command: ["calrissian"]
          args:
            - "--stdout"
            - "{{stdout}}"
            - "--stderr"
            - "{{stderr}}"
            - "--max-ram"
            - "{{max_ram}}"
            - "--max-cores"
            - "{{max_cores}}"
            - "--tmp-outdir-prefix"
            - "{{tmp_outdir_prefix}}"
            - "--debug"
            # - "--leave-tmpdir"
            # - "--leave-container"
            - "--no-read-only"
            - "--outdir"
            - "{{outdir}}"
            - "{{argument1}}"
            - "{{argument2}}"
          volumeMounts:
            - mountPath: {{volumemount_tmpout_mount_path}}
              name: {{volumemount_tmpout_name}}
            - mountPath: {{volumemount_output_data_mount_path}}
              name: {{volumemount_output_data_name}}
            - name: cwl-config-volume
              mountPath: {{cwl_file_path}}
              subPath: cwl
            - name: inputs-config-volume
              mountPath: {{inputs_file_path}}
              subPath: inputs
          env:
            - name: CALRISSIAN_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

      restartPolicy: Never
      volumes:
        - name: {{volumemount_tmpout_name}}
          persistentVolumeClaim:
            claimName: {{volumemount_tmpout_name}}
        - name: {{volumemount_output_data_name}}
          persistentVolumeClaim:
            claimName: {{volumemount_output_data_name}}
        - name: cwl-config-volume
          configMap:
            name: cwl-config
        - name: inputs-config-volume
          configMap:
            name: inputs-config
